#!/bin/sh

# If needed, add permission to make this file executable | chmod +x start
# Warning: the file acme.json must have chmod 600 privilege

echo; echo "If not existing, create our network ..."

if [ ! "$(docker network ls --filter name=ntw_front -q)" ];then
  docker network create --driver overlay --subnet 10.11.10.0/24 --opt encrypted ntw_front
  sleep 2
fi

docker volume create minio1-data
docker volume create minio2-data
docker volume create minio3-data
docker volume create minio4-data

echo; echo "Show network..."
docker network ls | grep "ntw_"

echo; echo "Start the stacks ..."

# traefik
docker stack deploy toolproxy -c toolproxy.yml
sleep 2

#webapps
docker stack deploy toolweb -c toolweb.yml
sleep 2

#Minio (storage)
docker stack deploy toolminio -c toolminio.yml
sleep 2

echo; echo "docker stack ls ..."
docker stack ls
sleep 2

echo; echo;

# Check services deployment
MIN=1
MAX=8
for ACTION in $(seq $MIN $MAX); do
  echo
  echo "docker service ls | Check $ACTION" of $MAX; echo;
	docker service ls && echo && sleep 2;
done

# Check traefik logs
echo; echo "docker service logs -f proxy_traefik ..."
docker service logs -f toolproxy_traefik