version: '3.2'

services:

  php:
    image: php:alpine
    labels:
      - "traefik.backend=php"
      - "traefik.frontend.rule=PathPrefix:/php"
      - "traefik.port=80"
      - "traefik.docker.network=ntw_front"
      - "traefik.backend.loadbalancer.method=wrr"
      - "traefik.backend.loadbalancer.swarm=true"
      - "traefik.weight=10"
    networks:
      - ntw_front
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s

networks:
  ntw_front:
    external: true